name: openrampette by opencare
markdown: kramdown
baseurl:
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-sitemap
  - jekyll-paginate
paginate: 10
paginate_path: /blog/page:num/

#this part configures the header in homepage

title: openrampette
tagline: this is the repo for the openrampette project
buttons:
  - text: View on GitHub
    link: https://github.com/opencarecc/openrampette
  - text: Download .zip
    link: https://github.com/opencarecc/openrampette/zipball/master
  - text: Build your own!
    link: https://github.com/opencarecc/openrampette/wiki
